feat: SLO resource
SquadcastHub/terraform-provider-squadcast-deprecated pull request #13
Opened 2022-06-16 21:21 UTC by roshan8

2022-07-13 09:54 UTC, dheeraj-squadcast requested changes

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/api/client.go
> +
Please revert, we have other ways of calling get and post methods

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +			"org_id": {
Not required, see client.OrgID

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +			"owner_type": {
remove this, it's always going to be "team", let's not burden the user

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +				Optional: true,
move this up, difficult to see

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"owner_type": {
remove

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"slo_id": {
no need to have this, this is got from slo resource itself

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"owner_type": {
remove

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"slo_id": {
remove

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +				Computed:     true,
why optional and computed?

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +				Computed:     true,
why optional and computed?

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +				Type:        schema.TypeInt,
why optional and computed?

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"users": {
inconsistent naming - if it's id, suffix with _id, and if plural, _ids

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"squads": {
inconsistent naming - if it's id, suffix with _id, and if plural, _ids

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"service": {
inconsistent naming - if it's id, suffix with _id, and if plural, _ids

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"team_id": {
remove,

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +						"team_id": {
remove

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/provider/resource_slo.go
> +				ValidateFunc: tf.ValidateObjectID,
set forcenew = true

2022-07-13 09:54 UTC, dheeraj-squadcast commented on internal/tf/state.go
> +		if !ok {
there are nested ifs + duplicated setids

replace the whole thing with a type switch followed by a SetID

2022-07-13 09:54 UTC, dheeraj-squadcast commented on docs/data-sources/squadcast_squad.md
> +subcategory: ""
please remove docs from this PR

2022-07-14 18:32 UTC, roshan8 commented on internal/provider/resource_slo.go
> +				Computed:     true,
If SLO is of type fixed then the user will enter `start date` and `end date`
When SLO is of type rolling then this field is not considered.

2022-07-14 18:40 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"users": {
sure, corrected

2022-07-14 18:40 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"squads": {
done

2022-07-14 18:40 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"service": {
done

2022-07-16 15:51 UTC, roshan8 commented on internal/api/client.go
> +
done

2022-07-16 15:51 UTC, roshan8 commented on internal/provider/resource_slo.go
> +			"org_id": {
done

2022-07-16 15:51 UTC, roshan8 commented on internal/provider/resource_slo.go
> +			"owner_type": {
removed

2022-07-16 15:51 UTC, roshan8 commented on internal/provider/resource_slo.go
> +				Optional: true,
done

2022-07-16 15:51 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"owner_type": {
done

2022-07-16 15:51 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"slo_id": {
done

2022-07-16 15:51 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"owner_type": {
done

2022-07-16 15:52 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"slo_id": {
done

2022-07-16 15:54 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"slo_id": {
The user not required to add this now, being added before making the call.

2022-07-16 15:55 UTC, roshan8 commented on internal/provider/resource_slo.go
> +				Computed:     true,
If SLO is of type fixed then the user will enter start date and end date
When SLO is of type rolling then this field is not considered.

2022-07-16 15:57 UTC, roshan8 commented on internal/provider/resource_slo.go
> +				Type:        schema.TypeInt,
its required if slo type is rolling, we need to pass duration_in_days.
and API response contains `start, end time and duration in days` no matter whether slo is fixed or rolling.

2022-07-16 15:57 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"team_id": {
done

2022-07-16 15:58 UTC, roshan8 commented on internal/provider/resource_slo.go
> +						"team_id": {
done, owner_id only required at the top level now

2022-07-16 15:58 UTC, roshan8 commented on internal/provider/resource_slo.go
> +				ValidateFunc: tf.ValidateObjectID,
done

2022-07-16 15:59 UTC, roshan8 commented on internal/tf/state.go
> +		if !ok {
changed

2022-07-16 15:59 UTC, roshan8 commented on docs/data-sources/squadcast_squad.md
> +subcategory: ""
removed content from docs directory

2022-07-18 14:27 UTC, merged